#username=kim980304@naver.com
#password=kimjeff98()
#username=kim980304@gmail.com
#password=ilmr lwwp yeyo fkjr

db.url=jdbc:mariadb://amorparami.cafe24.com:3306/amorparami?serverTimezone=Asia/Seoul
db.username=amorparami
db.password=goott!@345
email.username=kim980304@gmail.com
email.password=ilmr lwwp yeyo fkjr